Explicitly mention new output.ecmaVersion default
webpack/changelog-v5 pull request #12
Opened 2019-10-23 22:04 UTC by salemhilal

I'm in the process of migrating to v5 now and introducing ES6 syntax would output broken builds for our legacy users. It may be worth calling out the new `output.ecmaVersion` setting and it's default value explicitly in the migration guide.

2019-10-24 20:47 UTC, Lyrkan commented
Already done there: https://github.com/webpack/changelog-v5#improved-code-generation

2019-10-24 20:50 UTC, salemhilal commented
@Lyrkan it's in the changelog yes, but it's not in the migration guide. Following the migration guide, I wouldn't have known to update this as part of my migration had I not ran a build and seen the ES6 code.

2019-10-25 12:52 UTC, matheus1lva requested changes

2019-10-25 12:52 UTC, PlayMa256 commented on MIGRATION GUIDE.md
> +By default, Webpack's boilerplate code uses ES2015 syntax to build smaller bundles. If your build targets environments that don't support this syntax (like IE11), you'll need to set `output.ecmaVersi
```suggestion
By default, Webpack's runtime code uses ES2015 syntax to build smaller bundles. If your build targets environments that don't support this syntax (like IE11), you'll need to set `output.ecmaVersion: 5` to revert to ES5 syntax.
```

2019-10-25 12:52 UTC, PlayMa256 commented on MIGRATION GUIDE.md
> +## Disable ES2015 syntax in boilerplate code, if necessary
```suggestion
## Disable ES2015 syntax in runtime code, if necessary
```

2019-10-26 16:56 UTC, ematipico approved these changes

2019-10-28 12:06 UTC, matheus1lva approved these changes

2019-10-28 16:42 UTC, merged

2019-10-28 22:13 UTC, salemhilal commented
Thank you!