asset modules and json parser
webpack/changelog-v5 pull request #15
Opened 2019-12-04 10:55 UTC by smelukov

add more info about asset modules and custom parser for json

2019-12-04 12:21 UTC, lencioni approved these changes

2019-12-04 12:23 UTC, rishabh3112 approved these changes
LGTM

2019-12-06 11:59 UTC, jamesgeorge007 approved these changes

2019-12-06 12:10 UTC, rishabh3112 requested changes
@smelukov left a suggestion. Typescript notation looks better to me here.

2019-12-06 12:10 UTC, rishabh3112 commented on README.md
> +* The `asset` module type which is similar to the `file-loader`/`url-loader`/`raw-loader` (`experiments.asset`) (since alpha.19)
```suggestion
* The `asset` module type which is similar to the `file-loader`|`url-loader`|`raw-loader` (`experiments.asset`) (since alpha.19)
```

2019-12-06 12:17 UTC, smelukov commented
can we merge it?

2019-12-06 12:43 UTC, jamesgeorge007 approved these changes

2019-12-06 12:44 UTC, merged